### ISSUE TITLE
Create DB with odo 10

### ISSUE THREAD

**Issue by disaster37** [odoo/docker#106]
When I run postgres on docker container (official image) and I run odoo 10 on docker container (official image), I get some error when I create database without data.

The database name, user and password are set to `test`.

```
QWebException: 'ascii' codec can't decode byte 0xe2 in position 2530: ordinal not in range(128)Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn    return compiled(self, append, values, options, log)  File "<template>", line 1, in template_web_webclient_bootstrap_11  File "<template>", line 3, in body_call_content_10UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2530: ordinal not in range(128)
Error to render compiling AST
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2530: ordinal not in range(128)
Template: web.webclient_bootstrapPath: /templates/t/t/t[1]/t[9]
Node: <t t-call="web.webclient_script"/>```

**Comment by Fenkiou** [comment]
@disaster37 Please describe all your steps one by one to help people reproduce because I never encountered this issue.

**Comment by thomas15v** [comment]
Works fine with docker-compose. I would try to re-pull `docker pull odoo:10`.
```yml
version: '2'
services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
  odoo:
    image: odoo:10
    links:
      - db
    ports:
      - 80:8069
```
