### ISSUE TITLE
run as user "odoo" lead to writing volume failed

### ISSUE THREAD

**Issue by Foreverflying** [odoo/docker#109]
hi
I mount a volume directory to /var/lib/odoo，the error shows that access is denied.
then I learned about the docker volume machanism, just found neither chmod nor chown affects volume directorys. In my system, when mounting a host directory, the owner will always be root, the mode keeps 755, so the writing won't succeed.

so i think just use root is ok, chown, chmod, and mkdir -p /mnt/extra-addons are not necessary.
and use
ENTRYPOINT ["bash", "/entrypoint.sh"]
you needn't chmod for entrypoint.sh

**Comment by thomas15v** [comment]
The volume is already defined in the docker file. I don't see why you would wanna mount the volume to a local folder. Also if you make use of docker-compose for example it will remount the old volume back to the new container if you update it.

Also it's incorrect that the owner will always be root. The thing with docker is that each container has it's own user list. I believe you can fix the folder using this command:
`docker exec -u root <odooContainerId> chown odoo:odoo -R /var/lib/odoo`

**Comment by Spike-Lee** [comment]
Hey, I got a same problem
when I tried to mount Odoo:
```
grep: /etc/odoo/openerp-server.conf: Permission denied
grep: /etc/odoo/openerp-server.conf: Permission denied
grep: /etc/odoo/openerp-server.conf: Permission denied
grep: /etc/odoo/openerp-server.conf: Permission denied
Traceback (most recent call last):
  File "/usr/bin/openerp-server", line 2, in <module>
    import openerp
  File "/usr/lib/python2.7/dist-packages/openerp/__init__.py", line 61, in <module>
    import addons
ImportError: No module named addons
```

So, I added this in Dockerfile:
```
RUN chmod +x /etc/odoo/openerp-server.conf
```

but it's not works..result is same above...
Host is Synology NAS : Linux version 3.10.102 (root@build4) (gcc version 4.9.3 20150311 (prerelease) (crosstool-NG 1.20.0) )

Except NAS, like ubuntu 16.04 or Mac Sierra, it works very well.

**Comment by thomas15v** [comment]
Hi @Spike-Lee.

Dockerfile commands do not work on volumes since the modified file isn't available when the container is being build. 

You could try to execute `chmod o+r openerp-server.conf` on your file that you mounted. 

Also I recommend that you use a docker management tool like docker-compose to mount these files. I put some of my frequently used files in this [repo](https://github.com/thomas15v/odoo_docker/tree/master/docker_compose_overwrite_config).

**Comment by Spike-Lee** [comment]
@thomas15v
Thanks for your comment.

Unfortunately, the container is not running because of that, I cannot execute command.
```
$ docker-compose up -d
Creating conall_db_1
Creating conall_web_1
$ 
```
`conall_web_1` is odoo image name. At this moment, `conall_web_1`is not mounted.

And I have used a `docker-compose.yml` already:
```
version: '2'
services:
  web:
    image: kafkalen20/kafkaodoo9:init
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./source:/usr/lib/python2.7/dist-packages/openerp
  db:
    ports:
      - "5432:5432"
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:

```
