### ISSUE TITLE
role "odoo" does not exist

### ISSUE THREAD

**Issue by pascencio** [odoo/docker#180]
Hi everyone,

I'm trying to execute odoo follow the instructions from [Docker hub](https://hub.docker.com/_/odoo/). I'm writing a simple docker-compose file for this:

```yaml
version: "3"
services:
  odoo:
    image: odoo
    ports:
      - 8069:8069
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=odoo
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
```
Then execute the command ``docker-compose up``. The terminal give me this output.

```shell
2018-03-20 18:36:06,830 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
```
The problem comes when I try to access to the URL http://localhost:8069, for Odoo admin console.

```shell
db_1    | FATAL:  role "odoo" does not exist
odoo_1  | 2018-03-20 18:47:27,539 1 INFO ? odoo.sql_db: Connection to the database failed
```
Thanks in advance!
