### ISSUE TITLE
Port binding issue with nginx reverse proxy

### ISSUE THREAD

**Issue by weeger** [odoo/docker#185]
Hi,

As I posted an issue on the nginx reverse proxy repository here https://github.com/jwilder/nginx-proxy/issues/1127, I post the specific part for Odoo here.

I am not able to use Odoo with a binded port when I use it with https://github.com/jwilder/nginx-proxy. It works when ports biding is like `<customPort>:<customPort>`, but never when ports is on `<customPort>:<defaultAppPort>`.

First working example, with no proxy and customized port, I can access to my odoo with `http://myIP:8888`

```yml
version: '2.0'

services:
  odoo:
    depends_on:
    - odoo_postgres
    environment:
      DB_ENV_POSTGRES_PASSWORD: thisIsAReallyNotSecurePassword!
      DB_ENV_POSTGRES_USER: default
      DB_PORT_5432_TCP_ADDR: odoo_postgres
      DB_PORT_5432_TCP_PORT: '7080'
    image: odoo:11.0
    ports:
    - 8888:8069/tcp
    restart: always

  odoo_postgres:
    command: -p 7080
    container_name: odoo_postgres
    environment:
      PGPORT: '7080'
      POSTGRES_DB: odoo
      POSTGRES_PASSWORD: thisIsAReallyNotSecurePassword!
      POSTGRES_USER: default
    image: postgres:10.3
    ports:
    - 7080:7080/tcp
    restart: always
```

Using prody server and keeping default odoo port (`8069`), I can access to my odoo with `http://odoo.wex`

```yml

version: '2.0'

services:
  odoo:
    depends_on:
    - odoo_postgres
    environment:
      DB_ENV_POSTGRES_PASSWORD: thisIsAReallyNotSecurePassword!
      DB_ENV_POSTGRES_USER: default
      DB_PORT_5432_TCP_ADDR: odoo_postgres
      DB_PORT_5432_TCP_PORT: '7080'
      VIRTUAL_HOST: odoo.wex
      VIRTUAL_PORT: '8069'
    expose:
    - '8069'
    image: odoo:11.0
    networks:
      reverseproxy_wex_net: null
    ports:
    - 8069:8069/tcp
    restart: always

  odoo_postgres:
    command: -p 7080
    container_name: odoo_postgres
    environment:
      PGPORT: '7080'
      POSTGRES_DB: odoo
      POSTGRES_PASSWORD: thisIsAReallyNotSecurePassword!
      POSTGRES_USER: default
    image: postgres:10.3
    networks:
      reverseproxy_wex_net: null
    ports:
    - 7080:7080/tcp
    restart: always

networks:
  reverseproxy_wex_net:
    external: true

```

But does not work when using a custom port (`8888`), I can only access to my odoo with `http://odoo.wex:8888`, and `http://odoo.wex` gives me a `502 Bad Gateway` error.

```yml
version: '2.0'

services:
  odoo:
    depends_on:
    - odoo_postgres
    environment:
      DB_ENV_POSTGRES_PASSWORD: thisIsAReallyNotSecurePassword!
      DB_ENV_POSTGRES_USER: default
      DB_PORT_5432_TCP_ADDR: odoo_postgres
      DB_PORT_5432_TCP_PORT: '7080'
      VIRTUAL_HOST: odoo.wex
      VIRTUAL_PORT: '8888'
    expose:
    - '8888'
    image: odoo:11.0
    networks:
      reverseproxy_wex_net: null
    ports:
    - 8888:8069/tcp
    restart: always

  odoo_postgres:
    command: -p 7080
    container_name: odoo_postgres
    environment:
      PGPORT: '7080'
      POSTGRES_DB: odoo
      POSTGRES_PASSWORD: thisIsAReallyNotSecurePassword!
      POSTGRES_USER: default
    image: postgres:10.3
    networks:
      reverseproxy_wex_net: null
    ports:
    - 7080:7080/tcp
    restart: always

networks:
  reverseproxy_wex_net:
    external: true

```

There is the configuration :

```text
# odoo.wex
upstream odoo.wex {
                                ## Can be connect with "reverseproxy_wex_net" network
                        # odoo_odoo_1
                        server 172.16.238.5:8888;
}
server {
        server_name odoo.wex;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://odoo.wex;
        }
}
```

And the proxy error log :

```text
nginx.1    | 2018/05/01 13:23:38 [error] 208#208: *38 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.10.2, server: odoo.wex, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.16.238.5:8888/favicon.ico", host: "odoo.wex", referrer: "http://odoo.wex/"
nginx.1    | odoo.wex 172.20.10.2 - - [01/May/2018:13:23:38 +0000] "GET /favicon.ico HTTP/1.1" 502 576 "http://odoo.wex/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
```
