### ISSUE TITLE
Dataloss on restart

### ISSUE THREAD

**Issue by KDederichs** [odoo/docker#200]
Hey,

I want to use the docker image as development environment but sadly it seems to loose web configuration data on container restart.

I've pretty much used your default docker-compose config:

```yaml
version: '3.4'
services:
  web:
    image: odoo:11.0
    depends_on:
    - db
    ports:
    - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./modules:/mnt/extra-addons:rw
  db:
    image: postgres:9.4
    environment:
    - POSTGRES_PASSWORD=odoo
    - POSTGRES_USER=odoo
    - PGDATA=/var/lib/postgresql/data/odoo_data
    volumes:
      - db-data:/var/lib/postgresql/odoo_data:rw
volumes:
  db-data: {}
  odoo-web-data: {}

```

Does anyone know how to fix that?
