### ISSUE TITLE
wait-for-psql.py update broke my install

### ISSUE THREAD

**Issue by jwaes** [odoo/docker#278]
Since i pulled the new odoo:12 image, my odoo installation no longer starts

```
version: '2'
services:
  web:
    image: odoo:12
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - odoo
      - web
    environment:
      VIRTUAL_HOST : ${HOSTNAME}
      LETSENCRYPT_HOST : ${HOSTNAME}
      LETSENCRYPT_EMAIL : jaco@example.com
      VIRTUAL_PORT : 8069
    volumes:
      - web-conf:/etc/odoo
      - web-addons:/mnt/extra-addons
      - web-lib:/var/lib/odoo
      - web-log:/var/log/odoo

  db:
    image: postgres:10
    restart: unless-stopped
    networks:
      - odoo
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
    web-conf:
    web-addons:
    web-lib:
    web-log:
    db-data:

networks:
    odoo:
        driver: bridge
    web:
        external:
            name: web

```

i get the following error :

```
web_1  | usage: wait-for-psql.py [-h] --db_host DB_HOST --db_port DB_PORT --db_user
web_1  |                         DB_USER --db_password DB_PASSWORD [--timeout TIMEOUT]
web_1  | wait-for-psql.py: error: the following arguments are required: --db_host, --db_port, --db_user, --db_password
odoo_web_1 exited with code 2
```
Since the latest release had to do with this wait-for script i think a bug has been introduced

Starting with the previous image id hardcoded gives no problem.

**Comment by ChSch3000** [comment]
Same here. Our Docker builds with the base image odoo:12 stopped working since the wait-for update.
`FROM: odoo@sha256:dc9381042a1fa33e132ffd9d0008ab9161baaa0f72016debb947f81b467f7fa6` 
solves my problem.

**Comment by jwaes** [comment]
I reverted back to my last working image (the one from october 17th)

```
version: '2'
services:
  web:
    image: sha256:5ee30a7dd6fb5c9581af1f42fd9bfb9164bae461dbf7f5dc8a36f87a528eb21a
```
