### ISSUE TITLE
Install Odoo 12 Enterprise w/Docker

### ISSUE THREAD

**Issue by aev-treming** [odoo/docker#291]
What can I do if I want to install Odoo Enterprise using Docker?

**Comment by Sirfanas** [comment]
Hi,
You have to get Enterprise addons on your server, then you have to bind a volume mount point on your container so it see this folder, and add it in conf files.

Here's is the step:
I'll consider you are working under /opt/odoo (Just adapt to your system config)

```
git clone git@github.com:odoo/enterprise.git -b 12.0
# Change 12.0 by the version you need
```

If you use docker run / create command:
`
docker run/create [all your parameter] --volume=/opt/odoo/enterprise:/mnt/enterprise odoo:12.0
`

If you use a docker-compose file:
```
services:
    odoo:
        image: odoo:12.0
        volume:
             - ./enterprise:/mnt/enterprise
...
```

Then in your odoo.conf you have to edit addons_path and add /mnt/enterprise

Restart your container and create a new database, it should be in enterprise !
