### ISSUE TITLE
[Feature Request] Improve security by using docker secret for password

### ISSUE THREAD

**Issue by lonix1** [odoo/docker#302]
Please add support for docker secrets for passwords. Most major apps (and all databases) support this.

So instead of this:
````yml
version: "3.7"
services:

  postgresql:
    environment:
      POSTGRES_PASSWORD: foo
    # ...

  odoo:
    environment:
      PASSWORD: foo
````

We can do this:
````yml
version: "3.7"
services:

  postgresql:
    secrets:
      - postgresql_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/odoo_postgresql_password
    # ...

  odoo:
    secrets:
      - postgresql_password
    environment:
      PASSWORD_FILE: /run/secrets/odoo_postgresql_password

  secrets:
    postgresql_password:
      file: odoo_postgresql_password
````

This is more secure. Most secure database deployments do it like this, so odoo is the weak link in the chain (as we need to put the password in plaintext).

Here are [the docs](https://docs.docker.com/compose/compose-file/#secrets-configuration-reference).

**Comment by gn-jgeerds** [comment]
Duplicated #143

**Comment by lonix1** [comment]
So what? That one has hardly any info. This one should be preferred as it clearly explains what needs to be done, and links to the appropriate docs.

**Comment by llacroix** [comment]
@lonix1 you can check my fork if you need that It's already supported

**Comment by llacroix** [comment]
That said, defining the environment variable PGPASSFILE should be enough as such:

```
  odoo:
    secrets:
      - postgresql_password
    environment:
      PGPASSFILE: /run/secrets/odoo_postgresql_password              # unsupported

  secrets:
    postgresql_password:
      file: odoo_postgresql_password
```

Tought... The official images forces you to pass a password to check for connection to postgres.. But in reality it's not necessary if ENV variables are defined pg connect can be used as an empty string as done in odoo itself.
