### ISSUE TITLE
Add python3-pandas install to Dockerfile

### ISSUE THREAD

**Issue by jigzstar** [odoo/docker#311]
Is it possible to add this to the dockerfile, possibly?
https://github.com/odoo/docker/blob/f116a674ca62595d0fbf1ded206ec2e4d962ebf0/13.0/Dockerfile#L20

It will help me not having to log into the container and install it each time.

**Comment by d-fence** [comment]
I'm sorry to say no.
We cannot adapt this generic Dockerfile for each custom use case.
You could use our Dockerfile as a base four your specific case.

**Comment by jigzstar** [comment]
Okay, cool got it. It's actually needed for the open hrms plugin, but not mentioned.

**Comment by rauleb** [comment]
@jigzstar I create a dockerfile extending the original and install the pandas there.

Dockerfile
```
FROM odoo:13.0

SHELL ["/bin/bash", "-xo", "pipefail", "-c"]

ENV LANG C.UTF-8

USER root

RUN apt-get update

RUN apt-get install python3-pandas -y
```
and I run it with 

docker-compose.yml
```
version: "3"
services:
  odoo:
    container_name: odoo
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    ports:
      - "8069"
```

hope it helps
