### ISSUE TITLE
How to connect to the host database？

### ISSUE THREAD

**Issue by Etren** [odoo/docker#343]
I have PostgreSQL service running on the host, how do I connect to the host database service during the creation of the odoo container?

**Comment by ichux** [comment]
```
POSTGRES_PASSWORD=odoo
POSTGRES_USER=odoo
DB_PORT_5432_TCP_ADDR=172.30.0.2
DB_PORT_5432_TCP_PORT=5432
```
I have added sample variables for you to alter to taste. This worked for me using Odoo 11

**Comment by Etren** [comment]
> > > ```
> > > POSTGRES_PASSWORD=odoo
> > > POSTGRES_USER=odoo
> > > DB_PORT_5432_TCP_ADDR=172.30.0.2
> > > DB_PORT_5432_TCP_PORT=5432
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I have added sample variables for you to alter to taste. This worked for me using Odoo 11
> > 
> > 
> > Thank you for your reply! Do you add variables through `-e`?
> 
> You can do that in your docker-compose.yml there where you would add the environment variables for your postgres container

Do I need to map an external port for the odoo container to connect to port 5432 of the host?

**Comment by mimusica** [comment]
> > > > ```
> > > > POSTGRES_PASSWORD=odoo
> > > > POSTGRES_USER=odoo
> > > > DB_PORT_5432_TCP_ADDR=172.30.0.2
> > > > DB_PORT_5432_TCP_PORT=5432
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > I have added sample variables for you to alter to taste. This worked for me using Odoo 11
> > > 
> > > 
> > > Thank you for your reply! Do you add variables through `-e`?
> > 
> > 
> > You can do that in your docker-compose.yml there where you would add the environment variables for your postgres container
> 
> Do I need to map an external port for the odoo container to connect to port 5432 of the host?

if you run only 1 odoo and 1 postgres,
then odoo will look for a container "db" to connect to on it's virtual docker network.

e.g.
```yml
version: '3.5'
services:
  db:
      image: postgres
      <other config>
      environment:
        - <environment variables>
        - ...
  odoo:
      image: odoo:<version number>
      <other config>
```

**Comment by darm-torres** [comment]
In my experience, Docker default creates a separate sub-network for every run of a container.

You can add the `network: host` flag to your docker-compose file.
This way your container will run within the host network. Which is also the network of your database.
```
version: '3.4'
serivces:
  some_service:
  build:
    network: host
    ...
```

Then, in the odoo.conf you can configure the host database connection details.

![image](https://user-images.githubusercontent.com/79444834/197098758-50b6fde0-5e37-4393-84a8-23b33af0f493.png)
