### ISSUE TITLE
Can odoo image support arm?

### ISSUE THREAD

**Issue by whileom** [odoo/docker#349]
I'm trying dev odoo with apple silicon

**Comment by hoangtrann** [comment]
> I'm trying dev odoo with apple silicon

Hey there, how is your journey so far? I would love to develop odoo on mac air m1 with 8gb of ram to see how it goes

**Comment by whileom** [comment]
> > I'm trying dev odoo with apple silicon
> 
> Hey there, how is your journey so far? I would love to develop odoo on mac air m1 with 8gb of ram to see how it goes

now I develop Odoo(12 and 13) with source install and change some version in requirement.txt

Pillow to 8.1.0
reportlab to 3.5.59

and setting terminal (in my case using iTerm) "Open using Rosetta" 

if you wanna use docker it work too, install docker preview [https://docs.docker.com/docker-for-mac/apple-m1/](Docker)
no problem with postgres but odoo you must pull image by add  using `--platform linux/amd64` like
`docker pull odoo:14 --platform linux/amd64`


hope this help

**Comment by brandon-blb** [comment]
Hi.

I would just like to know if you got odoo working with the docker image on the M1 chip?

I am a Odoo developer and use docker. I am considering of getting a M1 Macbook but only if this works in docker.

**Comment by alxolivares** [comment]
Hello @brandon-blb 
I've install the Apple M1 tech preview build available [here](https://docs.docker.com/docker-for-mac/apple-m1/#download) and finally I used the following compose file to get Odoo up and running without problem:

```
version: "3.7"
services:
    odoo:
        image: odoo:14.0
        platform: linux/amd64
        container_name: odoo14
        depends_on:
            - postgresql
        tty: true
        stdin_open: true
        ports:
            - "8069:8069"
        volumes:
            - ./addons:/mnt/extra-addons
            - ./conf:/etc/odoo
        environment:
            - HOST=postgres12
    postgresql:
        image: postgres:12.4
        container_name: postgres12
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
```
The `--platform` option recommended by @whileom save my life! 🤘 

![image](https://user-images.githubusercontent.com/13812335/110052577-8ea7ce00-7d36-11eb-84ca-eb540d10f5a4.png)

Hope this help!

**Comment by brandon-blb** [comment]
@alxolivares Thank you. 

Cannot describe how much your feedback means to me. Ordering my M1 today :)

@whileom Can you maybe explain what the `--platform` flag does? Is it something new with the preview build of docker?

**Comment by alxolivares** [comment]
@brandon-blb 
I'm glad this helps you

According to the [documentation](https://docs.docker.com/compose/compose-file/compose-file-v2/#platform) `--platform` indicates which version of the image will be pulled and/or on which platform. Unlike postgres, odoo does not have yet images available for other architecture than `linux/amd64` if you try to make a pull without specifying this parameter you will get an error.

![image_01](https://user-images.githubusercontent.com/13812335/110630248-e6ee2e00-8183-11eb-8311-37f4cad1576a.png)
![image_02](https://user-images.githubusercontent.com/13812335/110630265-ec4b7880-8183-11eb-815b-ee9bb76bbc6a.png)

It was an unknown option to me but now I know. :+1:

Kind regards

**Comment by iqbalthea** [comment]
> Hello @brandon-blb
> I've install the Apple M1 tech preview build available [here](https://docs.docker.com/docker-for-mac/apple-m1/#download) and finally I used the following compose file to get Odoo up and running without problem:
> 
> ```
> version: "3.7"
> services:
>     odoo:
>         image: odoo:14.0
>         platform: linux/amd64
>         container_name: odoo14
>         depends_on:
>             - postgresql
>         tty: true
>         stdin_open: true
>         ports:
>             - "8069:8069"
>         volumes:
>             - ./addons:/mnt/extra-addons
>             - ./conf:/etc/odoo
>         environment:
>             - HOST=postgres12
>     postgresql:
>         image: postgres:12.4
>         container_name: postgres12
>         environment:
>             - POSTGRES_DB=postgres
>             - POSTGRES_PASSWORD=odoo
>             - POSTGRES_USER=odoo
> ```
> 
> The `--platform` option recommended by @whileom save my life! 🤘
> 
> ![image](https://user-images.githubusercontent.com/13812335/110052577-8ea7ce00-7d36-11eb-84ca-eb540d10f5a4.png)
> 
> Hope this help!

Do you have any step to install odoo 12 with docker? i'm still confused and keep getting this error:
![image](https://user-images.githubusercontent.com/45877085/111398976-f37c0480-86f6-11eb-8a9a-c4ade9191264.png)

Thank you.

**Comment by alxolivares** [comment]
Hello @iqbalthea 
The following compose file should work

```
version: "3.7"
services:
    odoo:
        image: odoo:12.0
        platform: linux/amd64
        container_name: odoo12
        depends_on:
            - postgresql
        tty: true
        stdin_open: true
        ports:
            - "8069:8069"
        volumes:
            - ./addons:/mnt/extra-addons
            - ./conf:/etc/odoo
        environment:
            - HOST=postgres10
    postgresql:
        image: postgres:10
        container_name: postgres10
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
```
![image](https://user-images.githubusercontent.com/13812335/111400568-55604e00-86a6-11eb-838b-82f29e94b27c.png)

Like a said before it's mandatory specify the `platform: linux/amd64` parameter to avoid the error that you mention above.

Regards
