### ISSUE TITLE
Odoo ReverseProxy Traefik

### ISSUE THREAD

**Issue by siddjellali** [odoo/docker#368]
Hello, 

When i host odoo behind a reverse proxy (Traefik), i got 500 error on all css file (style complication failed). 
Do you have any idea how to solve this ?

Odoo 14.0-20210427 (Community Edition)

![image](https://user-images.githubusercontent.com/3965823/116908481-3e1ff480-ac43-11eb-92e5-6588ea30717b.png)

My docker compose :

```
version: "3.7"

########################### NETWORKS
networks:
  t2_proxy:
    external: true
  erp_net:
    external: true
########################### SERVICES

services:
  odoo:
    container_name: odoo
    image: odoo:14
    restart: on-failure
    depends_on:
      - db
    networks:
      t2_proxy:
      erp_net:
    environment:
      - TZ=Europe/Paris
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.erp-intra-rtr.entrypoints=adm-https"
      - "traefik.http.routers.erp-intra-rtr.rule=HostHeader(`odoo.local.com`)"
      ## HTTP Services
      - "traefik.http.routers.erp-intra-rtr.service=erp-intra-svc"
      - "traefik.http.services.erp-intra-svc.loadbalancer.server.scheme=http"
      - "traefik.http.services.erp-intra-svc.loadbalancer.server.port=8069"
      - "traefik.http.routers.erp-intra-rtr.tls=true"
      - "traefik.http.routers.erp-intra-rtr.tls.certresolver=dns-cloudflare"
    volumes:
      - data:/var/lib/odoo
      - config:/etc/odoo
      - addons:/mnt/extra-addons

  db:
    container_name: odoo_db
    image: postgres:10
    networks:
      - erp_net
    environment:
      - TZ=Europe/Paris
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - data_db:/var/lib/postgresql/data/pgdata
      
volumes:
  data:
  config:
  addons:
  data_db:
```

I have also enable **proxy_mode = True** in odoo.conf without any changes.
Thanks in advance.
