### ISSUE TITLE
AttributeError: module 'odoo' has no attribute 'cli' when using docker-compose volumes

### ISSUE THREAD

**Issue by DanielLagin** [odoo/docker#379]
Hi, 

I am using docker-compose:
```
services:
  web:
    platform: linux/x86_64
    restart: always
    image: odoo:13.0
    #command: -d dev
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      #- ./odoo:/usr/lib/python3/dist-packages/odoo
      - ./addons:/mnt/extra-addons
      - ./addons/_lib:/mnt/_lib
      - ./config:/etc/odoo
      - ./backups:/var/tmp
      - ./debug:/usr/lib/python3.5/debug
  db:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
```

Everything works fine, unless I want to map into volumes /usr/lib/python3/dist-packages/odoo:
```
volumes:
  - ./odoo:/usr/lib/python3/dist-packages/odoo
```

Output from docker-compose up:

```
Traceback (most recent call last):

File "/usr/bin/odoo", line 8, in <module>

odoo.cli.main()

AttributeError: module 'odoo' has no attribute 'cli'
```

My idea is to control odoo version without creating my own image with dockerfile and changing argument ODOO_RELEASE.

Am I doing something wrong?

Thanks.
