### ISSUE TITLE
Data doesn't persist when using ´docker-compose down´

### ISSUE THREAD

**Issue by manuelaguirre** [odoo/docker#391]
I get redirected to the database manager (which I assume is because my data was not persisted) when I do `docker-compose down`

My `docker-compose.yml`:

```yml
version: '3.1'

services:
  app:
    image: odoo:latest
    ports:
      - "8069:8069"
    networks:
      - prod
    depends_on: 
      - db
      
  db:
    image: postgres:13
    ports:
      - "8079:5432"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    networks:
      - prod
    restart: unless-stopped


  testapp:
    image: odoo:latest
    ports:
      - "7069:8069"
    networks:
      - dev
    depends_on: 
      - testdb
    environment:
    - HOST=testdb
    - USER=odootest
    - PASSWORD=odootest
    volumes:
    - test_addons:/mnt/extra-addons
  testdb:
    image: postgres:13
    ports:
      - "8080:5432"
    environment:
      - POSTGRES_USER=odootest
      - POSTGRES_PASSWORD=odootest
      - POSTGRES_DB=postgres
    networks:
      - dev
    restart: unless-stopped

volumes:
    test_addons:
            driver: local
            driver_opts:
                o: bind
                type: none
                device: ./addons/



networks:
  prod:
    driver: bridge
  dev:
    driver: bridge

```
