### ISSUE TITLE
I had a permission problem when I mounted the data volume. Trying to specify a user also didn't work.

### ISSUE THREAD

**Issue by imaxun** [odoo/docker#480]
<img width="608" alt="image" src="https://github.com/odoo/docker/assets/29112991/0fc0d9a9-1907-4032-b6e9-7008a7a55bc4">

<img width="1220" alt="image" src="https://github.com/odoo/docker/assets/29112991/dd084eb1-4614-4ff4-9191-677c50108181">

**Comment by amh-mw** [comment]
I don't recognize the format of your YAML file, but in my own docker-compose.yaml:

```yaml
services:
  web:
    # This seems similar to your volumeMounts and lets the container mount the volume
    volumes:
      - odoo-data:/var/lib/odoo
# This creates the volume
volumes:
  odoo-data:
    # Nothing here as I am creating a volume from scratch
```

Are you missing the second part?
