### ISSUE TITLE
Debug in PyCharm - where is the source code in the odoo image?

### ISSUE THREAD

**Issue by mikerocker11** [odoo/docker#516]
Hi,

I recently switched from a source-based installation to a Docker-based setup. Here's the docker-compose.yml file I'm using:

```
version: '3.1'
services:
  web:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
volumes:
  odoo-web-data:
  odoo-db-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass
```
When I was using the source-based installation, I was able to configure PyCharm correctly for debugging. My question is:

Where can I find the source code for the odoo:17.0 image so that I can assign it to a volume, view the code in PyCharm, and set breakpoints?
