### ISSUE TITLE
Failed to load resource: the server responded with a status of 404

### ISSUE THREAD

**Issue by edxz** [odoo/docker#92]
Static files failed to load with the following error message when using docker image

> Failed to load resource: the server responded with a status of 404 (NOT FOUND)

this is my docker-compose.yml

```
odoo:
  image: odoo:latest
  ports:
    - 8069:8069
  links:
    - db
  environment:
    - PGHOST=db
    - PGUSER=odoo
    - PGPASSWORD=odoo
  volumes:
    - ./config:/etc/odoo
    - ./addons:/mnt/extra-addons
db:
  image: postgres:latest
  environment:
    - POSTGRES_USER=odoo
    - POSTGRES_PASSWORD=odoo
  ports:
   - 5433:5432
```

and this is my config:
```
[options]
addons_path = /usr/lib/python2.7/dist-packages/openerp/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
auto_reload = True
; admin_passwd = admin
; csv_internal_sep = ,
; db_maxconn = 64
; db_name = False
; db_template = template1
; dbfilter = .*
; debug_mode = False
; email_from = False
; limit_memory_hard = 2684354560
; limit_memory_soft = 2147483648
; limit_request = 8192
; limit_time_cpu = 60
; limit_time_real = 120
; list_db = True
; log_db = False
; log_handler = [':INFO']
; log_level = info
; logfile = None
; longpolling_port = 8072
; max_cron_threads = 2
; osv_memory_age_limit = 1.0
; osv_memory_count_limit = False
; smtp_password = False
; smtp_port = 25
; smtp_server = localhost
; smtp_ssl = False
; smtp_user = False
; workers = 0
; xmlrpc = True
; xmlrpc_interface = 
; xmlrpc_port = 8069
; xmlrpcs = True
; xmlrpcs_interface = 
; xmlrpcs_port = 8071
```
This is the screenshot:
![selection_065](https://cloud.githubusercontent.com/assets/6778749/21538866/eb455428-cdd3-11e6-9b8f-850d1d73f951.png)
